^XA

^FX ==== PLAIN LABELS TEMPLATE: TEXT AT THE TOP, IMAGE BELOW ====

^FX ==== TOP SECTION: CATEGORY TEXT LINE 1 ====
^FO0,40
^CF0,110
^FB812,1,0,C,0
^FD{{CWRD1}}\&^FS

^FX ==== TOP SECTION: CATEGORY TEXT LINE 2 ====
^FO0,150
^CF0,110
^FB812,1,0,C,0
^FD{{CWRD2}}\&^FS

^FX ==== LOWER SECTION: MONOCHROME GRAPHIC CELL ====
^XGE:IMGTEMP.GRF,1,1^FS

^XZ
